### ISSUE TITLE
lcd.print and lcd.font morecomplex examples

### ISSUE THREAD

**Issue by pastukhov** [m5stack/micropython-m5stack#13]
Hello!
I'm trying to get transparent text.
But getting: ```TypeError: extra positional arguments given```
My code is: ```lcd.font(lcd.FONT_Ubuntu, 0, 1)```
Pleas provide more complex example of lcd.print and lcd.font functions with all the arguments.

**Comment by 0x1abin** [comment]
Hi! Sorry to reply you late!

lcd.font(font [,rotate, transparent, fixedwidth, dist, width, outline, color])
lcd.print(text[,x, y, color, rotate, transparent, fixedwidth, wrap])

print transparent text:
```python
lcd.font(lcd.FONT_Ubuntu, transparent=True)
lcd.print('hello')
# or
lcd.print("hello", transparent=True)
```

**Comment by pastukhov** [comment]
Great, thanks!
