### ISSUE TITLE
FrameBuffer object

### ISSUE THREAD

**Issue by pastukhov** [m5stack/micropython-m5stack#14]
Please implement a FrameBuffer object from micropython to be able show images from binary buffer? not only file.

**Comment by 0x1abin** [comment]
Hi! Sorry to reply you late! 
the FrameBuffer module is Enable at latest version.
```python
import framebuf
mlogo = framebuf.FrameBuffer(bytearray(17 * 17 * 2), 17, 17, framebuf.RGB565)
```
