### ISSUE TITLE
PWM sample code in README.md is wrong (duty range is not 0-1024)

### ISSUE THREAD

**Issue by stnk20** [m5stack/micropython-m5stack#23]
Sample code in README.md contains wrong information.
pwm.duty(666) is out of range. pwm.duty is in range 0-100, not 0-1024

```
import machine
pwm = machine.PWM(26)
pwm.freq(5000)
pwm.duty(666)
```

And servo.py has same issue:
https://github.com/m5stack/M5Cloud/blob/2da5a04668a754847128376d1422de1ef89f5764/lib/servo.py#L31

**Comment by 0x1abin** [comment]
Thanks for your feedback, I fixed it.
