### ISSUE TITLE
How to exit the while loop by clicking buttonA.wasPressed ()

### ISSUE THREAD

**Issue by AlexanderSemenov1** [m5stack/micropython-m5stack#25]
How to exit the while loop by clicking buttonA.wasPressed ()

**Comment by yeyeto2788** [comment]
Try adding a ` break` within the `while`. Something like:
```python
while True:
    do something
    if buttonA.wasPressed():
        break
```

Or even better
```python 
while not buttonA.wasPressed():
    do something
```

**Comment by AlexanderSemenov1** [comment]
This method does not work
while true:
    do something
    if buttonA.wasPressed():
        break

I'll try the second method, I'll tell you the result.

**Comment by yeyeto2788** [comment]
You are right, I made a mistake on the syntax (already fixed it) it should be `True` instead of `true` (Notice the capital T)

Reading the documentation you can also use callback on the button press:
https://github.com/m5stack/M5Cloud#button

**Comment by AlexanderSemenov1** [comment]
The second way also does not work.
Here is an example of this code

from m5stack import lcd, buttonA, buttonB, buttonC
import micropython, machine, time

#x = lcd.winsize()
#d = utime.localtime()
clok_on = False
clik = False
buttonA.wasPressed()


def but_a():
    clok_on = False
    lcd.clear(lcd.OLIVE)
    lcd.setCursor(0, 0)
    lcd.setColor(lcd.RED, lcd.OLIVE)  # Красный
    lcd.line(0, 15, 100, 15, 0xFF00FF)
    lcd.rect(75, 75, 50, 50, 0x0000FF, lcd.GREEN)
    lcd.circle(100, 100, 50, 0xFF8000)
    lcd.roundrect(160, 100, 80, 80, 10, lcd.BLACK) 
    
def stop():
    clok_on = False

def clock():
    clok_on = True
    
    rtc = machine.RTC()
    print("Synchronize time from NTP server ...")
    lcd.println("Synchronize time from NTP server ...")
    rtc.ntp_sync(server="ru.pool.ntp.org", tz="CET-3CEST,M3.5.0,M10.5.0/3")

    lcd.clear(lcd.BLUE)
    lcd.setColor(lcd.BLACK, lcd.BLUE)
    lcd.font(lcd.FONT_Comic, fixedwidth=True, dist=16, width=2)
   
   
    while True :
        d = time.strftime("%d-%m-%Y", time.localtime())
        t = time.strftime("%H:%M:%S", time.localtime())
        lcd.print(d, lcd.CENTER, 50)
        lcd.print(t, lcd.CENTER, 130)
        time.sleep(1)
        if buttonA.wasPressed():
            break
        
        
        
    #_thread.start_new_thread('Clock', clock, ())

lcd.clear(lcd.GREEN)
lcd.setCursor(100, 100)
lcd.setColor(lcd.BLACK, lcd.GREEN)
lcd.print('Hello')

def but_b():
   clok_on = False
   lcd.clear(lcd.ORANGE)
   lcd.setCursor(100, 100)
   lcd.setColor(lcd.BLACK, lcd.ORANGE)
   lcd.print('World')
   return()    

#def but_c():
#    cl = clock()
#   lcd.clear()
 #   lcd.print(str(cl))
  #  #return() 

buttonA.wasPressed(but_a)
buttonB.wasPressed(but_b)
buttonC.wasPressed(clock)
#buttonA.releasedFor(1.2, may_meny_A)

**Comment by yeyeto2788** [comment]
I notice you have the `time.sleep(1)` before reading the button. Might be that you are pressing on the sleep time. 

I have removed it and change a bit the code order, try this:

```python
from m5stack import lcd, buttonA, buttonB, buttonC
import micropython, machine, time

clok_on = False
clik = False
buttonA.wasPressed()

def but_a():
    clok_on = False
    lcd.clear(lcd.OLIVE)
    lcd.setCursor(0, 0)
    lcd.setColor(lcd.RED, lcd.OLIVE) # Красный
    lcd.line(0, 15, 100, 15, 0xFF00FF)
    lcd.rect(75, 75, 50, 50, 0x0000FF, lcd.GREEN)
    lcd.circle(100, 100, 50, 0xFF8000)
    lcd.roundrect(160, 100, 80, 80, 10, lcd.BLACK)

def but_b():
    clok_on = False
    lcd.clear(lcd.ORANGE)
    lcd.setCursor(100, 100)
    lcd.setColor(lcd.BLACK, lcd.ORANGE)
    lcd.print('World')
    return()

def but_c():
    cl = clock()
    lcd.clear()
    lcd.print(str(cl))
    return()

def stop():
    clok_on = False

def clock():
    clok_on = True

rtc = machine.RTC()
print("Synchronize time from NTP server ...")
lcd.println("Synchronize time from NTP server ...")
rtc.ntp_sync(server="ru.pool.ntp.org", tz="CET-3CEST,M3.5.0,M10.5.0/3")

lcd.clear(lcd.BLUE)
lcd.setColor(lcd.BLACK, lcd.BLUE)
lcd.font(lcd.FONT_Comic, fixedwidth=True, dist=16, width=2)


while True :
    d = time.strftime("%d-%m-%Y", time.localtime())
    t = time.strftime("%H:%M:%S", time.localtime())
    lcd.print(d, lcd.CENTER, 50)
    lcd.print(t, lcd.CENTER, 130)
    if buttonA.wasPressed():
        break

print("Wujuuuu out of the while loop")
```

**Comment by AlexanderSemenov1** [comment]
Does not work. Does not come out of the loop.
Try to execute this code, I shortened it.

from m5stack import lcd, buttonA, buttonB, buttonC
import micropython, machine, time

def but_a():
    clok_on = False
    lcd.clear(lcd.OLIVE)
    lcd.setCursor(0, 0)
    lcd.setColor(lcd.RED, lcd.OLIVE) # Красный
    lcd.line(0, 15, 100, 15, 0xFF00FF)
    lcd.rect(75, 75, 50, 50, 0x0000FF, lcd.GREEN)
    lcd.circle(100, 100, 50, 0xFF8000)
    lcd.roundrect(160, 100, 80, 80, 10, lcd.BLACK)

def clock():
    rtc = machine.RTC()
    print("Synchronize time from NTP server ...")
    lcd.println("Synchronize time from NTP server ...")
    rtc.ntp_sync(server="ru.pool.ntp.org", tz="CET-3CEST,M3.5.0,M10.5.0/3")

    lcd.clear(lcd.BLUE)
    lcd.setColor(lcd.BLACK, lcd.BLUE)
    lcd.font(lcd.FONT_Comic, fixedwidth=True, dist=16, width=2)

    while True :
        d = time.strftime("%d-%m-%Y", time.localtime())
        t = time.strftime("%H:%M:%S", time.localtime())
        lcd.print(d, lcd.CENTER, 50)
        lcd.print(t, lcd.CENTER, 130)
        if buttonA.wasPressed(but_a):
            break

#print("Wujuuuu out of the while loop")
buttonA.wasPressed(but_a)
buttonC.wasPressed(clock)

**Comment by AlexanderSemenov1** [comment]
from m5stack import lcd, buttonA, buttonB, buttonC
import micropython, machine, time

def but_a():
       clok_on = False
       lcd.clear(lcd.OLIVE)
       lcd.setCursor(0, 0)
       lcd.setColor(lcd.RED, lcd.OLIVE) # Красный
       lcd.line(0, 15, 100, 15, 0xFF00FF)
       lcd.rect(75, 75, 50, 50, 0x0000FF, lcd.GREEN)
       lcd.circle(100, 100, 50, 0xFF8000)
       lcd.roundrect(160, 100, 80, 80, 10, lcd.BLACK)

def clock():
        rtc = machine.RTC()
        print("Synchronize time from NTP server ...")
        lcd.println("Synchronize time from NTP server ...")
        rtc.ntp_sync(server="ru.pool.ntp.org", tz="CET-3CEST,M3.5.0,M10.5.0/3")

        lcd.clear(lcd.BLUE)
        lcd.setColor(lcd.BLACK, lcd.BLUE)
        lcd.font(lcd.FONT_Comic, fixedwidth=True, dist=16, width=2)

        while True :
                 d = time.strftime("%d-%m-%Y", time.localtime())
                  t = time.strftime("%H:%M:%S", time.localtime())
                  lcd.print(d, lcd.CENTER, 50)
                  lcd.print(t, lcd.CENTER, 130)
                  if buttonA.wasPressed(but_a):
                                break

print("Wujuuuu out of the while loop")
buttonA.wasPressed(but_a)
buttonC.wasPressed(clock)

**Comment by yeyeto2788** [comment]
What is actually happening is that you're using the callback `but_a` when the button is pressed, if you just want to exit do not perform the callback.

**Comment by AlexanderSemenov1** [comment]
This loop is enclosed in a function, I want to switch to another function but can not leave the loop. A week I suffer with this or a bug of some kind or knowledge is not enough.

**Comment by AlexanderSemenov1** [comment]
Sorry for the translation from Russian

**Comment by AlexanderSemenov1** [comment]
The inserted code is aligned to the right

**Comment by AlexanderSemenov1** [comment]
There are two functions but_a () and clock (). The clock () function has a loop that I can not leave.

**Comment by yeyeto2788** [comment]
If I understood correctly you might want something like this:

```python
from m5stack import lcd, buttonA, buttonB, buttonC
import micropython, machine, time

def but_a():
    clok_on = False
    lcd.clear(lcd.OLIVE)
    lcd.setCursor(0, 0)
    lcd.setColor(lcd.RED, lcd.OLIVE) # Красный
    lcd.line(0, 15, 100, 15, 0xFF00FF)
    lcd.rect(75, 75, 50, 50, 0x0000FF, lcd.GREEN)
    lcd.circle(100, 100, 50, 0xFF8000)
    lcd.roundrect(160, 100, 80, 80, 10, lcd.BLACK)

def clock():
    rtc = machine.RTC()
    print("Synchronize time from NTP server ...")
    lcd.println("Synchronize time from NTP server ...")
    rtc.ntp_sync(server="ru.pool.ntp.org", tz="CET-3CEST,M3.5.0,M10.5.0/3")

    lcd.clear(lcd.BLUE)
    lcd.setColor(lcd.BLACK, lcd.BLUE)
    lcd.font(lcd.FONT_Comic, fixedwidth=True, dist=16, width=2)

    while True :
        d = time.strftime("%d-%m-%Y", time.localtime())
        t = time.strftime("%H:%M:%S", time.localtime())
        lcd.print(d, lcd.CENTER, 50)
        lcd.print(t, lcd.CENTER, 130)
        if buttonA.wasPressed():
            but_a()
                            
while True:
    buttonC.wasPressed(clock)
```

**Comment by AlexanderSemenov1** [comment]
from m5stack import lcd, buttonA, buttonB, buttonC
import micropython, machine, time

def but_a():
    clok_on = False
    lcd.clear(lcd.OLIVE)
    lcd.setCursor(0, 0)
    lcd.setColor(lcd.RED, lcd.OLIVE) # Красный
    lcd.line(0, 15, 100, 15, 0xFF00FF)
    lcd.rect(75, 75, 50, 50, 0x0000FF, lcd.GREEN)
    lcd.circle(100, 100, 50, 0xFF8000)
    lcd.roundrect(160, 100, 80, 80, 10, lcd.BLACK)

def clock():
    rtc = machine.RTC()
    print("Synchronize time from NTP server ...")
    lcd.println("Synchronize time from NTP server ...")
    rtc.ntp_sync(server="ru.pool.ntp.org", tz="CET-3CEST,M3.5.0,M10.5.0/3")

    lcd.clear(lcd.BLUE)
    lcd.setColor(lcd.BLACK, lcd.BLUE)
    lcd.font(lcd.FONT_Comic, fixedwidth=True, dist=16, width=2)

    while True :
        d = time.strftime("%d-%m-%Y", time.localtime())
        t = time.strftime("%H:%M:%S", time.localtime())
        lcd.print(d, lcd.CENTER, 50)
        lcd.print(t, lcd.CENTER, 130)
        if buttonA.wasPressed():
            but_a()
                            
buttonA.wasPressed(but_a)
buttonC.wasPressed(clock)

**Comment by AlexanderSemenov1** [comment]
from m5stack import lcd, buttonA, buttonB, buttonC
import micropython, machine, time

def but_a():
    clok_on = False
    lcd.clear(lcd.OLIVE)
    lcd.setCursor(0, 0)
    lcd.setColor(lcd.RED, lcd.OLIVE) # Красный
    lcd.line(0, 15, 100, 15, 0xFF00FF)
    lcd.rect(75, 75, 50, 50, 0x0000FF, lcd.GREEN)
    lcd.circle(100, 100, 50, 0xFF8000)
    lcd.roundrect(160, 100, 80, 80, 10, lcd.BLACK)

def clock():
    rtc = machine.RTC()
    print("Synchronize time from NTP server ...")
    lcd.println("Synchronize time from NTP server ...")
    rtc.ntp_sync(server="ru.pool.ntp.org", tz="CET-3CEST,M3.5.0,M10.5.0/3")

    lcd.clear(lcd.BLUE)
    lcd.setColor(lcd.BLACK, lcd.BLUE)
    lcd.font(lcd.FONT_Comic, fixedwidth=True, dist=16, width=2)

    while True :
        d = time.strftime("%d-%m-%Y", time.localtime())
        t = time.strftime("%H:%M:%S", time.localtime())
        lcd.print(d, lcd.CENTER, 50)
        lcd.print(t, lcd.CENTER, 130)
        if buttonA.wasPressed():
            but_a()
                            
buttonA.wasPressed(but_a)
buttonC.wasPressed(clock)

**Comment by AlexanderSemenov1** [comment]
Instead of recording
  while True:
     buttonC.wasPressed (clock)
write down
buttonA.wasPressed (but_a)
buttonC.wasPressed (clock)

**Comment by AlexanderSemenov1** [comment]
[test.txt](https://github.com/m5stack/M5Cloud/files/2335319/test.txt)

**Comment by yeyeto2788** [comment]
@AlexanderSemenov1  looking at the file you're still using the callback on the `while` loop within the `clock` function.

The code below will never reach the `break`.
```python
...
    while True :
        d = time.strftime("%d-%m-%Y", time.localtime())
        t = time.strftime("%H:%M:%S", time.localtime())
        lcd.print(d, lcd.CENTER, 50)
        lcd.print(t, lcd.CENTER, 130)
        if buttonA.wasPressed(but_a):
            break
```

Instead use the code below to reach the `break`:
```python
...
    while True :
        d = time.strftime("%d-%m-%Y", time.localtime())
        t = time.strftime("%H:%M:%S", time.localtime())
        lcd.print(d, lcd.CENTER, 50)
        lcd.print(t, lcd.CENTER, 130)
        if buttonA.wasPressed():
            break
```

If you want to exit of the while you have to change this. I don't really know what you really want to achieve and I'm not able to test your code because I don't have the board. 

If you want your code to be executed always running the `clock` function and every time you press the button it goes to the `but_a` function use the code below.

```python
    while True :
        d = time.strftime("%d-%m-%Y", time.localtime())
        t = time.strftime("%H:%M:%S", time.localtime())
        lcd.print(d, lcd.CENTER, 50)
        lcd.print(t, lcd.CENTER, 130)
        buttonA.wasPressed(but_a):
```

or use this:

```python
    while True :
        d = time.strftime("%d-%m-%Y", time.localtime())
        t = time.strftime("%H:%M:%S", time.localtime())
        lcd.print(d, lcd.CENTER, 50)
        lcd.print(t, lcd.CENTER, 130)
        if buttonA.wasPressed(but_a):
            but_a()
```

If what you're trying to do is a different thing try explaining a bit more your problem and the goal you want to achieve.

**Comment by AlexanderSemenov1** [comment]
The question is how to get out of the enclosed cycle?
If the cycle is not nested, then everything is perfectly worked!
For some reason, there is no reaction to the button pressing in the embedded cycle.

**Comment by yeyeto2788** [comment]
Try putting a `not` before the call to the `buttonA.wasPressed()` something like:
```python
if not buttonA.wasPressed():
            but_a()
```

**Comment by AlexanderSemenov1** [comment]
Ничего не выходит, все попробовал.
Если цикл while не заключен в функции то все прекрасно работает и без проблем выходит из цикла по break, а иначе помогает только перезагрузка модуля.
Nothing comes out, I tried everything.
If the while loop is not enclosed in a function, then everything works fine and without problems it breaks out of the loop, otherwise it only helps reboot the module.
It looks like some kind of bug in the button module.

**Comment by AlexanderSemenov1** [comment]
Everything turned out the way I wanted.
Incidentally, I understood the functions of the button library.
The reason for my anguish was in the poor description of the functions of the button library.
Many thanks to yeyeto2788 for trying to help.
And the wish to the developer of this library of buttons, do a more detailed description of the functions and what they do.

Here's an example of how I managed to stop the while while interacting with the button library.

from m5stack import buttonA, buttonC
import time

def score():
    i = 0
    while True:
        i+=1
        print(i)
        time.sleep(0.05)
        if buttonA.isPressed():
            break

buttonC.wasPressed(score)

**Comment by AlexanderSemenov1** [comment]
`from m5stack import buttonA, buttonC
import time

def score():
    i = 0
    while True:
        i+=1
        print(i)
        time.sleep(0.05)
        if buttonA.isPressed():
            break


buttonC.wasPressed(score)`

**Comment by AlexanderSemenov1** [comment]
Here's an example of how I managed to stop the while while interacting with the button library.
[test1.txt](https://github.com/m5stack/M5Cloud/files/2343607/test1.txt)
