### ISSUE TITLE
lcd.readPixel always returns 0xffffff

### ISSUE THREAD

**Issue by MinoruInachi** [m5stack/micropython-m5stack#4]
Firmware: m5cloud-20180102-v0.2.5.bin

MicroPython API lcd.readPixel() always returns 0xffffff in point within screen size.

```
MicroPython ESP32_LoBo_v2.0.8 - 2017-11-04 on M5Stack with ESP32
Type "help()" for more information.
>>> from m5stack import lcd
>>> lcd.clear()
>>> lcd.screensize()
(320, 320)
>>> hex(lcd.readPixel(0,0))
'0xffffff'
>>> hex(lcd.readPixel(100,100))
'0xffffff'
>>> hex(lcd.readPixel(319,319))
'0xffffff'
>>> hex(lcd.readPixel(320,320))
'0x0'
```

**Comment by 0x1abin** [comment]
hi, think you for your comment.
lcd.screensize function this bug will fix at next version.
lcd.readPixel is not support, because the LCD hardware is not connect the miso pin, sorry next version will remove it.

**Comment by MinoruInachi** [comment]
I confirmed that lcd.readPixel() was removed in v0.3.0 firmware.
Thanks.
